### ISSUE TITLE
Spellcheck doesn't work on any indented content

### ISSUE THREAD

**Issue by Archmonger** [pawamoy/mkdocs-spellcheck#13] opened 2022-11-02 07:24 UTC
**Describe the bug**
Nothing that is indented will get spellchecked, such as [mkdocs material admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage).

`mkdocs-spellcheck` is assuming all indented content are always codeblocks.

Here are some potential fixes:
1) Assume code blocks always fenced (using triple ticks  \`\`\` ). Indented code blocks have been fairly uncommon styling for a while now.
2) Create two separate toggles for `ignore_code` and `ignore_indents`. Could alleviate this issue. I personally don't use indents for code blocks anymore, especially due to `mkdocs-material`'s color formatted code blocks.
3) Create some some heuristic matching to determine "what is a code block".

**To Reproduce**
1. Install mkdocs-spellcheck
2. Install mkdocs-material
3. Create a admonition with a spelling error within the body

**Expected behavior**
Indented content should be spell checked

**Screenshots**
N/A

**System (please complete the following information):**
- `MkDocs SpellCheck` version: 0.2.1
- Python version: 3.10
- OS: Windows

**Additional context**
N/A

**Comment by pawamoy** [comment] 2022-11-02 08:22
Hello, thanks for the report!

I don't think the cause is what you describe. This plugin operates on HTML, not Markdown, so indented blocks transformed into admonitions have no reason to be skipped :thinking:

I'll take a look!

**Comment by Archmonger** [comment] 2022-11-02 08:30
One detail I forgot to mention is that `ignore_code=no` allows admonitions to be spelled checked. But obviously, all my actual code blocks end up spamming the console with warnings.

**Comment by pawamoy** [comment] 2022-11-02 16:33
Wow, there was a huge bug in the HTML stripper hahaha. For some reason I implemented a `handle_stoptag` method while it's actually called `handle_endtag`.

**Comment by pawamoy** [comment] 2022-11-02 17:35
Released in version 0.2.2 :slightly_smiling_face:

**Closed** 2022-11-02 17:40 UTC
